### ISSUE TITLE
Add slight window border

### ISSUE THREAD

**Issue by chriskuech** [ViktorQvarfordt/vscode-pitch-black-theme#3] opened 2019-04-08 18:28 UTC
It's annoying to have two overlapping VS Code windows with this theme because they merge together.  Please add a very faint border (`1px solid #333`) around the window like https://hyper.is/ does.

**Comment by ViktorQvarfordt** [comment] 2019-04-08 19:05
I agree, thanks! I see that I haven't pushed a fix for your other issue yet. Will fix both soon :)

**Comment by ViktorQvarfordt** [comment] 2019-04-08 20:18
I cannot reproduce this (using mac). For me the window already has a border, probably from the system-wide window theme in macOS. If you find the necessary change for linux/windows, feel free to make a PR.

**Closed as completed by ViktorQvarfordt** 2019-04-08 20:18 UTC
